spring.application.name=youtubeAiAgent
youtube.api.url=https://www.googleapis.com/youtube/v3/commentThreads
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent